services:
    _defaults:
        autoconfigure: true
        autowire: true

    Terminal42\ChangeLanguage\EventListener\DataContainer\UserLabelsListener: ~

    Terminal42\ChangeLanguage\EventListener\DataContainer\ArticleViewListener:
        calls:
            - ['setUrlParser', ['@Codefog\HasteBundle\UrlParser']]

    Terminal42\ChangeLanguage\EventListener\DataContainer\PageViewListener:
        calls:
            - ['setUrlParser', ['@Codefog\HasteBundle\UrlParser']]

    Terminal42\ChangeLanguage\EventListener\DataContainer\ParentChildViewListener:
        calls:
            - ['setUrlParser', ['@Codefog\HasteBundle\UrlParser']]
